In [200]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import random

In [201]:
dataset = pd.read_csv('C:/Users/andre/Desktop/AI/Research/clf-data.csv')

In [202]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 300 entries, 0 to 299
Data columns (total 5 columns):
id       300 non-null int64
h        300 non-null float64
w        300 non-null float64
a        300 non-null float64
class    300 non-null int64
dtypes: float64(3), int64(2)
memory usage: 11.8 KB


In [203]:
numColumns = len(dataset.columns)
numColumns

5

In [204]:
# Assuming the dataset has a designated label column
numAttributes = numColumns - 2
numAttributes

3

In [205]:
numRows = len(dataset.values)
numRows

300

In [324]:
numClusters = input("How many clusters? ")
numClusters = int(numClusters)

How many clusters? 3


In [477]:
numIterations = input("How many iterations (Each iteration returns cluster assignment for each attribute)")
numIterations = int(numIterations)

How many iterations (Each iteration returns cluster assignment for each attribute)75


In [478]:
# Creating numpy array of all attributes
df = dataset.iloc[:, 1 : -1]
attributes = df.to_numpy()
attributes

array([[ 61.3862987 , 156.5819631 ,  27.82902894],
       [ 73.10784274, 152.2668556 ,  27.75419412],
       [ 74.855714  , 142.0235767 ,  28.53491206],
       [ 57.27910161, 139.9321704 ,  16.08735256],
       [ 65.54026263, 155.8560188 ,  32.21540374],
       [ 75.70964122, 140.9013599 ,  31.82443146],
       [ 57.26831901, 152.4294117 ,  25.56111655],
       [ 66.01002537, 145.025775  ,  20.32538068],
       [ 69.55649329, 160.5707349 ,  22.92823779],
       [ 66.34706822, 143.5545551 ,  33.22827654],
       [ 57.94781467, 131.8286519 ,  26.9377956 ],
       [ 65.16519814, 149.871851  ,  18.7456253 ],
       [ 68.32418094, 141.2483302 ,  18.45556667],
       [ 57.95987779, 156.916624  ,  22.47223582],
       [ 71.50526433, 152.5120816 ,  22.45477794],
       [ 74.03286627, 174.9995455 ,  25.66650208],
       [ 65.54010477, 147.385015  ,  33.67390639],
       [ 61.81728115, 138.8550595 ,  31.63627129],
       [ 65.54037053, 139.2512871 ,  28.7401255 ],
       [ 73.32854865, 152.91493

In [479]:
minAttributes = np.amin(attributes, axis=0)
minAttributes

array([40.71455665, 74.12457452,  3.37779302])

In [480]:
maxAttributes = np.amax(attributes, axis =0)
maxAttributes

array([ 77.00444204, 191.6724014 ,  37.45023988])

In [481]:
# Function returns euclidean distance between two vectors
def euclideanDistance(vector1, vector2):
    dist = np.linalg.norm(vector1 - vector2)
    return dist

In [482]:
# Function returns the index of the cluster with the shortest distance to the inputted attribute vector
def assignedCluster(attribute):
    clusterIndex = 0
    minDistance = euclideanDistance(attribute, clusterCenters[0])
    for i in range(len(clusterCenters)):
        if (euclideanDistance(attribute, clusterCenters[i]) < minDistance):
            clusterIndex = i
            minDistance = euclideanDistance(attribute, clusterCenters[i])
    return clusterIndex

In [483]:
def centroid(attributeArray):
    return np.mean(attributeArray, axis = 0)

In [484]:
for i in range (30):
    # Using the min and max arrays as bounds, generate random arrays that fall within these constraints
    clusterCenters = []
    for i in range(numClusters):
        tempCluster = []
        for j in range(minAttributes.size):
            tempCluster.append(random.randint(round(minAttributes[j]), round(maxAttributes[j] + 1)))
        clusterCenters.append(tempCluster)
    clusterCenters

    for i in range(numIterations + 1):
        # Array of index values corresponding to the clusterCenters
        assignedClusters = []
        for attribute in attributes:
            assignedClusters.append(assignedCluster(attribute))


        # Creating dictionary to hold cluster numbers as keys and corresponding attribute indexes as values to group by cluster
        attributesByCluster = {}
        for i in range(numClusters):
            attributeIndexes = []
            for j in range(len(assignedClusters)):
                if (assignedClusters[j] == i):
                    attributeIndexes.append(j)
            attributesByCluster[i] = attributeIndexes



        # Replacing indexes in attributesByCluster by their actual attributes
        for indexList in list(attributesByCluster.values()):
            for i in range(len(indexList)):
                indexList[i] = attributes[indexList[i]]


        # Update clusterCenters
        for i in list(attributesByCluster.keys()):
            if(attributesByCluster[i]):
                clusterCenters[i] = centroid(np.asarray(attributesByCluster[i]))


    actualClusters = dataset.iloc[:,-1].to_numpy()

    # Using NMI as metric to measure model
    from sklearn.metrics.cluster import normalized_mutual_info_score
    print(normalized_mutual_info_score(actualClusters, assignedClusters))

0.8928277306427332
0.8928277306427332
0.899694587110345
0.8928277306427332
0.899694587110345
0.6532165182640899
0.8928277306427331
0.8928277306427332
0.8928277306427332
0.8928277306427332
0.8928277306427331
0.8928277306427332
0.8996945871103453
0.8928277306427332
0.8928277306427331
0.8928277306427332
0.8928277306427332
0.899694587110345
0.8928277306427331
0.899694587110345
0.8928277306427331
0.8928277306427332
0.8928277306427332
0.8928277306427332
0.8928277306427332
0.8928277306427331
0.8928277306427332
0.8996945871103453
0.8928277306427332
0.8928277306427332


In [485]:
#assignedClusters

In [449]:
#attributesByCluster